# Generated by Django 5.2.1 on 2025-05-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
    ]
